# -*- coding: utf-8 -*-
"""25083010041_Andika Putra A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njFChKwzqxsLOc8UterQTOLYRatr0qOj
"""

# @title Jaque-Bera
data = [12, 15, 14, 10, 18, 16, 13, 17, 11, 14]
n = len(data)

mean = sum(data) / n

selisih =[]
for x in data:
    selisih.append(x - mean)

m2 = 0
for d in selisih:
    m2 += d**2

m2 /= n

m3 = 0
for d in selisih:
    m3 += d**3

m4 = 0
for d in selisih:
    m4 += d**4

skewnes = m3 / (n * m2**1.5)

kurtosis = (m4 / (n * m2**2)) - 3

jb = (n/6) * (skewnes**2 + ((kurtosis - 3)**2) /4)

chi_square_critical = 5.991

if jb > chi_square_critical:
    keputusan = "Tolak H0: Data tidak berdistribusi normal"
else:
    keputusan = "Gagal tolak H0: Data berdistribusi  normal"

print("n =", n)
print("mean =", mean)
print("m2 =", m2)
print("m3 =", m3)
print("m4 =", m4)
print("kurtosis =", kurtosis)
print("skewness =", skewnes)
print("jb =", jb)
print("keputusan =", keputusan)



"""**Kolmogorov Smirnov**

---
Metode Kolmogorov-Smirnov (K-S) adalah uji statistik non-parametrik yang digunakan untuk menguji apakah suatu data mengikuti distribusi tertentu (misalnya distribusi normal) atau untuk membandingkan dua distribusi data. Uji ini dilakukan dengan mencari selisih maksimum antara fungsi distribusi kumulatif empiris sampel dan fungsi distribusi kumulatif teoritis.

Hipotesis yang digunakan:

* H₀ : Data berdistribusi normal.
* H₁ : Data tidak berdistribusi normal.

---
1. Rata-rata ($\bar{x}$) dan Simpangan Baku ($s$):
   $$\bar{x} = \frac{\sum x_i}{n}$$
   $$s = \sqrt{\frac{\sum (x_i - \bar{x})^2}{n-1}}$$

2. Transformasi ke Z-Score ($Z_i$):
   $$Z_i = \frac{x_i - \bar{x}}{s}$$

3. Fungsi Distribusi Kumulatif Empiris ($S(Z_i)$):
   $$S(Z_i) = \frac{i}{n}$$
   (di mana $i$ adalah urutan data ke-i setelah diurutkan)

4. Fungsi Distribusi Kumulatif Teoritis ($F(Z_i)$):
   Nilai peluang kumulatif dari distribusi normal baku untuk setiap nilai $Z_i$ (Area di bawah kurva normal $P(Z \le Z_i)$).

5. Statistik Uji Kolmogorov-Smirnov ($D$):
   Selisih antara probabilitas kumulatif empiris dan teoritis.
   $$D = \max |F(Z_i) - S(Z_i)|$$
"""

data = [12, 15, 14, 10, 18, 16, 13, 17, 11, 14]

n = len(data)

data_urut = sorted(data)

mean = sum(data) / n

selisih_mean = []
for x in data:
    selisih_mean.append(x - mean)

varians = 0
for d in selisih_mean:
    varians += d**2

varians /= n

std = varians**0.5

D = max(selisih)

D_kritis = 1.36 / (n**0.5)

if D > D_kritis:
    keputusan = "Tolak H0: Data tidak berdistribusi normal"
else:
    keputusan = "Gagal tolak H0: Data berdistribusi normal"

print("n =", n)
print("data_urut =", data_urut)
print("mean =", mean)
print("varians =", varians)
print("std =", std)
print("D =", D)
print("D_kritis =", D_kritis)
print("keputusan =", keputusan)

# @title f varian

data1 = [70, 75, 80, 72, 78]
data2 = [65, 85, 60, 90, 70]

n1 = len(data1)
n2 = len(data2)

mean1 = sum(data1) / n1
mean2 = sum(data2) / n2

jumlah_kuadrat1 = 0
for x in data1:
    jumlah_kuadrat1 += (x - mean1) **2
varians1 = jumlah_kuadrat1 / (n1 - 1)

jumlah_kuadrat2 = 0
for x in data2:
    jumlah_kuadrat2 += (x - mean2) **2
varians2 = jumlah_kuadrat2 / (n2 - 1)

if varians1 > varians2:
    f_hitung = varians1 / varians2
    df1 = n1 - 1
    df2 = n2 - 1
else:
    f_hitung = varians2 / varians1
    df1 = n2 - 1
    df2 = n1 - 1

from scipy.stats import f

alpha = 0.05
f_tabel = f.ppf(1 - alpha, df1, df2)

if f_hitung > f_tabel:
    keputusan = "Tolak H0: Varians tidak homogen"
else:
    keputusan = "Gagal tolak H0: Varians homogen"

print("n1 =", n1)
    print("n2 =", n2)
    print("mean1 =", mean1)
    print("mean2 =", mean2)
    print("varians1 =", varians1)
    print("varians2 =", varians2)
    print("f_hitung =", f_hitung)
    print("f_tabel =", f_tabel)
    print("keputusan =", keputusan)

"""**Uji Levene**

---
Uji Levene adalah uji statistik yang digunakan untuk mengetahui apakah varians dari dua atau lebih kelompok data bersifat homogen atau sama. Pada uji ini, H₀ menyatakan bahwa varians data homogen, sedangkan H₁ menyatakan varians data tidak homogen. Uji Levene lebih baik digunakan ketika data tidak berdistribusi normal.


---
1. Rata-rata Kelompok ($\bar{Y}_i$) atau Median Kelompok ($\tilde{Y}_i$):
   Uji Levene standar menggunakan nilai rata-rata kelompok ($i$).
   $$\bar{Y}_i = \frac{\sum_{j=1}^{n_i} Y_{ij}}{n_i}$$

2. Transformasi Data ke Nilai Deviasi Absolut ($Z_{ij}$):
   Menghitung seberapa jauh setiap data ($j$) menyimpang dari rata-rata kelompok ($i$) dalam nilai mutlak (selalu positif).
   $$Z_{ij} = |Y_{ij} - \bar{Y}_i|$$

3. Statistik Uji Levene ($W$ atau $F\text{-hitung}$):
   Menggunakan rumus Analysis of Variance (ANOVA) satu arah yang diterapkan pada data baru ($Z_{ij}$):
   $$W = \frac{(N - k)}{(k - 1)} \cdot \frac{\sum_{i=1}^{k} n_i (\bar{Z}_{i\cdot} - \bar{Z}_{\cdot\cdot})^2}{\sum_{i=1}^{k} \sum_{j=1}^{n_i} (Z_{ij} - \bar{Z}_{i\cdot})^2}$$

   *Keterangan:*
   * $k$ = Jumlah kelompok (pada kasus ini $k = 2$, yaitu data1 dan data2).
   * $N$ = Total seluruh data dari semua kelompok ($n_1 + n_2 = 5 + 5 = 10$).
   * $n_i$ = Jumlah data pada kelompok ke-$i$.
   * $\bar{Z}_{i\cdot}$ = Rata-rata nilai $Z$ pada kelompok ke-$i$.
   * $\bar{Z}_{\cdot\cdot}$ = Rata-rata nilai $Z$ keseluruhan secara total.

---



"""

data1 = [70, 75, 80, 72, 78]
data2 = [65, 85, 60, 90, 70]

# Jumlah data
n1 = len(data1)
n2 = len(data2)
N = n1 + n2

# Mean data1
mean1 = sum(data1) / n1

# Mean data2
mean2 = sum(data2) / n2

# Deviasi absolut data1
z1 = []
for x in data1:
    z1.append(abs(x - mean1))

# Deviasi absolut data2
z2 = []
for x in data2:
    z2.append(abs(x - mean2))

# Rata-rata deviasi
zbar1 = sum(z1) / n1
zbar2 = sum(z2) / n2

# Rata-rata deviasi keseluruhan
zbar = (sum(z1) + sum(z2)) / N

# Pembilang
pembilang = (
    n1 * (zbar1 - zbar)**2 +
    n2 * (zbar2 - zbar)**2
)

# Penyebut
penyebut = 0

for z in z1:
    penyebut += (z - zbar1)**2

for z in z2:
    penyebut += (z - zbar2)**2

# Jumlah kelompok
k = 2

# Statistik Levene
W = ((N-k)/(k-1)) * (pembilang/penyebut)

# F tabel
Ftabel = 5.32

# Output
print("Mean data1 =", mean1)
print("Mean data2 =", mean2)

print("Z1 =", z1)
print("Z2 =", z2)

print("Zbar1 =", zbar1)
print("Zbar2 =", zbar2)
print("Zbar =", zbar)

print("Pembilang =", pembilang)
print("Penyebut =", penyebut)

print("W hitung =", W)
print("F tabel =", Ftabel)

if W < Ftabel:
    print("Kesimpulan: Varians homogen")
else:
    print("Kesimpulan: Varians tidak homogen")

# @title Independensi Chi-square
observasi = [[30, 20],[15, 35]]
jumlah_baris = len(observasi)
jumlah_kolom = len(observasi[0])

total_baris = []
for baris in observasi:
    total_baris.append(sum(baris))

total_kolom = []
for j in range(jumlah_kolom):
    total = 0
    for i in range(jumlah_baris):
        total += observasi[i][j]
    total_kolom.append(total)

grand_total = sum(total_baris)

harapan = []
for i in range(jumlah_baris):
    harapan_baris = []
    for j in range(jumlah_kolom):
        eij = (total_baris[i] * total_kolom[j] / grand_total)
        harapan_baris.append(eij)
    harapan.append(harapan_baris)

chi_square = 0
for i in range(jumlah_baris):
    for j in range(jumlah_kolom):
        O = observasi[i][j]
        E = harapan[i][j]
        chi_square += ((O - E)**2) / E

df = (jumlah_baris - 1) * (jumlah_kolom - 1)

alpha = 0.05
from scipy.stats import chi2
chi_square_tabel = chi2.ppf(1 - alpha, df)

if chi_square > chi_square_tabel:
    keputusan = "Tolak H0: Terdapat Hubungan"
else:
    keputusan = "Gagal tolak H0: Tidak terdapat Hubungan"

print("jumlah_baris =", jumlah_baris)
print("jumlah_kolom =", jumlah_kolom)
print("grand_total =", grand_total)
print("harapan =", harapan)
print("chi_square =", chi_square)
print("chi_square_tabel =", chi_square_tabel)
print("keputusan =", keputusan)

"""**Fisher Exact**

---
Uji Fisher's Exact Test merupakan uji signifikansi statistik yang digunakan untuk menentukan apakah terdapat hubungan atau asosiasi yang tidak terjadi secara acak antara dua variabel kategorikal yang disajikan dalam tabel kontingensi $2 \times 2$.

Berbeda dengan Uji Chi-Square yang menggunakan pendekatan aproksimasi (asimtotik), Fisher's Exact Test menghitung nilai probabilitas secara eksak, sehingga memberikan hasil yang lebih akurat pada kondisi tertentu. Uji ini sangat direkomendasikan dan menjadi pilihan utama ketika:

*   Ukuran sampel total relatif kecil ($N < 40$).
*   Terdapat sel pada tabel kontingensi yang memiliki frekuensi harapan (expected frequency) kurang dari 5.

---
**Rumus Uji Kebolehan**

---
Uji Fisher's Exact Test menggunakan distribusi hipergeometrik untuk menghitung probabilitas eksak dari susunan data yang diamati dengan asumsi bahwa jumlah total pada setiap baris dan kolom (marginal totals) bersifat tetap (fixed). Dengan pendekatan ini, probabilitas setiap kemungkinan tabel kontingensi yang memiliki total baris dan kolom yang sama dapat dihitung secara tepat tanpa menggunakan pendekatan aproksimasi.

Misalkan terdapat tabel kontingensi $2 \times 2$ sebagai berikut:

| | Kolom 1 | Kolom 2 | Total Baris |
| :--- | :---: | :---: | :---: |
| **Baris 1** | $a$ | $b$ | $a + b$ |
| **Baris 2** | $c$ | $d$ | $c + d$ |
| **Total Kolom** | $a + c$ | $b + d$ | $n$ (Total Sampel) |

Rumus untuk menghitung probabilitas eksak ($p$) dari kombinasi angka tersebut adalah:

$$p = \frac{(a+b)! (c+d)! (a+c)! (b+d)!}{a! b! c! d! n!}$$

> **Catatan:** Simbol `!` menunjukkan nilai Faktorial (contoh: $4! = 4 \times 3 \times 2 \times 1 = 24$).







"""

data = [
    [30, 20],
    [15, 35]
]

a = data[0][0]
b = data[0][1]
c = data[1][0]
d = data[1][1]

baris1 = a + b
baris2 = c + d

kolom1 = a + c
kolom2 = b + d

n = a + b + c + d

def faktorial(x):
    hasil = 1

    for i in range(1, x + 1):
        hasil *= i

    return hasil

p = (
    faktorial(baris1)
    * faktorial(baris2)
    * faktorial(kolom1)
    * faktorial(kolom2)
) / (
    faktorial(a)
    * faktorial(b)
    * faktorial(c)
    * faktorial(d)
    * faktorial(n)
)

print("a =", a)
print("b =", b)
print("c =", c)
print("d =", d)

print("Total Baris 1 =", baris1)
print("Total Baris 2 =", baris2)

print("Total Kolom 1 =", kolom1)
print("Total Kolom 2 =", kolom2)

print("Grand Total =", n)

print("Peluang Fisher =", p)

